steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/knative-portability-2019/events', '.']
  dir: 'events'
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/knative-portability-2019/events']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'events', '--image', 'gcr.io/knative-portability-2019/events', '--region', 'us-central1','--platform', 'managed']
images:
- gcr.io/knative-portability-2019/events
